version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: webflux-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: devandre
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: medium-db
    volumes:
      - mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: devandre
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://devandre:password@mongodb:27017/
    depends_on:
      - mongodb

volumes:
  mongodb:
    driver: local